/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domen.Igrac;
import domen.Klub;
import domen.Liga;
import domen.Turnir;
import domen.Ucesnik;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeliTabela.ModelTabeleIgracaZaTurnir;
import modeliTabela.ModelTabeleListaTurnira;

/**
 *
 * @author Dule
 */
public class FormaGlavna extends javax.swing.JFrame {

    modeliTabela.ModelTabeleIgracaZaTurnir mtizt = new ModelTabeleIgracaZaTurnir();
    modeliTabela.ModelTabeleListaTurnira mtt = new ModelTabeleListaTurnira();

    /**
     * Creates new form FormaGlavna
     */
    public FormaGlavna() {
        initComponents();
        this.setSize(1550, 1000);

        ucitajPanel();
        ucitajMiSveKlubove();
        ucitajMiSveIgrace();
        ucitajMiSveLige();
        ucitajModelTabele();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTabelaTurniri = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaUtakmica = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaTabela = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaTurnira = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelNapraviTurnir = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaIgracaNaTurniru = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbIgrac = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbKlub = new javax.swing.JComboBox();
        btnKreirajTurnir = new javax.swing.JButton();
        btnDodajIgracaZaTurnir = new javax.swing.JButton();
        btnObrisiIgracaIzListeZaTurnir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNazivTurnira = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtNadimak = new javax.swing.JTextField();
        btnNapraviIgraca = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtImeKluba = new javax.swing.JTextField();
        btnNapraviKlub = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        spinerBrojZvezdica = new javax.swing.JSpinner();
        cmbLiga = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        panelStatistikaIgraca = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnNapraviTabeluMeni = new javax.swing.JButton();
        cmbTabeleMeni = new javax.swing.JButton();
        btnStatistikaMeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelTabelaTurniri.setLayout(null);

        tabelaUtakmica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaUtakmica);

        panelTabelaTurniri.add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 380, 129);

        tabelaTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaTabela);

        panelTabelaTurniri.add(jScrollPane3);
        jScrollPane3.setBounds(10, 230, 380, 155);

        tabelaTurnira.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelaTurnira);

        panelTabelaTurniri.add(jScrollPane4);
        jScrollPane4.setBounds(680, 50, 400, 380);

        jLabel11.setText("Tabela:");
        panelTabelaTurniri.add(jLabel11);
        jLabel11.setBounds(10, 210, 140, 16);

        jLabel12.setText("Lista utakmica:");
        panelTabelaTurniri.add(jLabel12);
        jLabel12.setBounds(10, 46, 87, 20);

        jLabel13.setText("Lista turnira");
        panelTabelaTurniri.add(jLabel13);
        jLabel13.setBounds(680, 20, 180, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        panelTabelaTurniri.add(jScrollPane6);
        jScrollPane6.setBounds(410, 70, 230, 310);

        jLabel14.setText("Igraci:");
        panelTabelaTurniri.add(jLabel14);
        jLabel14.setBounds(420, 50, 70, 20);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        panelTabelaTurniri.add(jSeparator1);
        jSeparator1.setBounds(650, 0, 20, 430);

        getContentPane().add(panelTabelaTurniri);
        panelTabelaTurniri.setBounds(10, 33, 1480, 950);

        panelNapraviTurnir.setLayout(null);

        tabelaIgracaNaTurniru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaIgracaNaTurniru);

        jLabel1.setText("Igrac:");

        cmbIgrac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Tim:");

        cmbKlub.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnKreirajTurnir.setText("Napravi turnir");
        btnKreirajTurnir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajTurnirActionPerformed(evt);
            }
        });

        btnDodajIgracaZaTurnir.setText("Dodaj");
        btnDodajIgracaZaTurnir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajIgracaZaTurnirActionPerformed(evt);
            }
        });

        btnObrisiIgracaIzListeZaTurnir.setText("Obrisi");
        btnObrisiIgracaIzListeZaTurnir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiIgracaIzListeZaTurnirActionPerformed(evt);
            }
        });

        jLabel10.setText("Naziv turnira:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnObrisiIgracaIzListeZaTurnir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDodajIgracaZaTurnir, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnKreirajTurnir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNazivTurnira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbIgrac, 0, 158, Short.MAX_VALUE)
                                .addComponent(cmbKlub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbKlub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajIgracaZaTurnir)
                    .addComponent(btnObrisiIgracaIzListeZaTurnir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtNazivTurnira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajTurnir)
                .addContainerGap())
        );

        panelNapraviTurnir.add(jPanel1);
        jPanel1.setBounds(6, 6, 500, 348);

        jLabel3.setText("Ime:");

        jLabel4.setText("Prezime:");

        jLabel5.setText("Nadimak:");

        btnNapraviIgraca.setText("Napravi igraca");
        btnNapraviIgraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNapraviIgracaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNadimak, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnNapraviIgraca, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNadimak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNapraviIgraca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNapraviTurnir.add(jPanel2);
        jPanel2.setBounds(532, 6, 344, 152);

        jLabel7.setText("Ime kluba:");

        btnNapraviKlub.setText("Napravi klub");
        btnNapraviKlub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNapraviKlubActionPerformed(evt);
            }
        });

        jLabel6.setText("Broj zvezdica");

        spinerBrojZvezdica.setModel(new javax.swing.SpinnerNumberModel(3.0d, 0.5d, 5.0d, 0.5d));

        cmbLiga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Liga:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnNapraviKlub, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addComponent(cmbLiga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtImeKluba)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(spinerBrojZvezdica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtImeKluba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinerBrojZvezdica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNapraviKlub)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelNapraviTurnir.add(jPanel3);
        jPanel3.setBounds(512, 170, 364, 138);

        getContentPane().add(panelNapraviTurnir);
        panelNapraviTurnir.setBounds(12, 37, 1480, 950);

        panelStatistikaIgraca.setLayout(null);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        panelStatistikaIgraca.add(jScrollPane5);
        jScrollPane5.setBounds(6, 74, 858, 217);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelStatistikaIgraca.add(jComboBox3);
        jComboBox3.setBounds(197, 36, 273, 26);

        jLabel8.setText("jLabel8");
        panelStatistikaIgraca.add(jLabel8);
        jLabel8.setBounds(6, 39, 173, 20);

        getContentPane().add(panelStatistikaIgraca);
        panelStatistikaIgraca.setBounds(6, 35, 1480, 950);

        btnNapraviTabeluMeni.setText("Kreiraj Turnir");
        btnNapraviTabeluMeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNapraviTabeluMeniActionPerformed(evt);
            }
        });
        getContentPane().add(btnNapraviTabeluMeni);
        btnNapraviTabeluMeni.setBounds(0, 0, 120, 32);

        cmbTabeleMeni.setText("Tabela");
        cmbTabeleMeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTabeleMeniActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTabeleMeni);
        cmbTabeleMeni.setBounds(111, 0, 110, 32);

        btnStatistikaMeni.setText("Statistika");
        btnStatistikaMeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistikaMeniActionPerformed(evt);
            }
        });
        getContentPane().add(btnStatistikaMeni);
        btnStatistikaMeni.setBounds(205, 1, 120, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajIgracaZaTurnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajIgracaZaTurnirActionPerformed
        Igrac i = (Igrac) cmbIgrac.getSelectedItem();
        Klub k = (Klub) cmbKlub.getSelectedItem();
        Ucesnik u = new Ucesnik(i, k, null, mtizt.getRowCount() + 1);
        mtizt.dodajUcesnika(u);
    }//GEN-LAST:event_btnDodajIgracaZaTurnirActionPerformed

    private void btnObrisiIgracaIzListeZaTurnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiIgracaIzListeZaTurnirActionPerformed
        int broj = tabelaIgracaNaTurniru.getSelectedRow();
        if (broj == -1) {
            JOptionPane.showMessageDialog(this, "Selektujte igraca koji zelite da obrisete!");
            return;
        }
        Ucesnik u = mtizt.getLista().get(broj);
        mtizt.obirisIzTabele(u);
    }//GEN-LAST:event_btnObrisiIgracaIzListeZaTurnirActionPerformed

    private void btnKreirajTurnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajTurnirActionPerformed
        ArrayList<Ucesnik> lista = (ArrayList<Ucesnik>) mtizt.getLista();
        String naziv = txtNazivTurnira.getText();
        if (naziv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Popunite polje naziv turnira!");
            return;
        }
        int maxID = Kontroler.getInstance().vratiMiZaTurnirID();
        Date d = new Date();
        Turnir t = new Turnir(maxID, naziv, d, null);
        txtNazivTurnira.setText("");
        boolean uspesnoTurnir = Kontroler.getInstance().napraviTurnir(t);
        for (Ucesnik ucesnik : lista) {
            ucesnik.setTurnir(t);
        }
        boolean uspesnoUcesnici = Kontroler.getInstance().unesiUcesnike(lista);
        if (uspesnoTurnir && uspesnoUcesnici) {
            JOptionPane.showMessageDialog(this, "Uspesno napravljen turnir!");
        } else {
            JOptionPane.showMessageDialog(this, "GRESKA!");
        }

    }//GEN-LAST:event_btnKreirajTurnirActionPerformed

    private void btnNapraviIgracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNapraviIgracaActionPerformed
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String nadimak = txtNadimak.getText();
        Igrac i = new Igrac(-1, ime, prezime, nadimak);
        txtIme.setText("");
        txtPrezime.setText("");
        txtNadimak.setText("");
        boolean uspesno = Kontroler.getInstance().unesiIgraca(i);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Uspesno napravljen igrac!");
            cmbIgrac.addItem(i);

            return;
        }
        JOptionPane.showMessageDialog(this, "GRESKA!");

    }//GEN-LAST:event_btnNapraviIgracaActionPerformed

    private void btnNapraviKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNapraviKlubActionPerformed
        String naziv = txtImeKluba.getText();
        Liga l = (Liga) cmbLiga.getSelectedItem();
        double brojZvezdica = (double) spinerBrojZvezdica.getValue();
        Klub k = new Klub(-1, naziv, l, brojZvezdica);
        txtImeKluba.setText("");
        boolean uspesno = Kontroler.getInstance().unesiKlub(k);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Uspesno napravljen klub!");
            cmbKlub.addItem(k);
            return;
        }
        JOptionPane.showMessageDialog(this, "GRESKA!");

    }//GEN-LAST:event_btnNapraviKlubActionPerformed

    private void btnNapraviTabeluMeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNapraviTabeluMeniActionPerformed
        panelNapraviTurnir.setVisible(true);
        panelStatistikaIgraca.setVisible(false);
        panelTabelaTurniri.setVisible(false);
    }//GEN-LAST:event_btnNapraviTabeluMeniActionPerformed

    private void cmbTabeleMeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTabeleMeniActionPerformed
        panelNapraviTurnir.setVisible(false);
        panelStatistikaIgraca.setVisible(false);
        panelTabelaTurniri.setVisible(true);
        ucitajTurnire();
    }//GEN-LAST:event_cmbTabeleMeniActionPerformed

    private void btnStatistikaMeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikaMeniActionPerformed
        panelNapraviTurnir.setVisible(false);
        panelStatistikaIgraca.setVisible(true);
        panelTabelaTurniri.setVisible(false);
    }//GEN-LAST:event_btnStatistikaMeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajIgracaZaTurnir;
    private javax.swing.JButton btnKreirajTurnir;
    private javax.swing.JButton btnNapraviIgraca;
    private javax.swing.JButton btnNapraviKlub;
    private javax.swing.JButton btnNapraviTabeluMeni;
    private javax.swing.JButton btnObrisiIgracaIzListeZaTurnir;
    private javax.swing.JButton btnStatistikaMeni;
    private javax.swing.JComboBox cmbIgrac;
    private javax.swing.JComboBox cmbKlub;
    private javax.swing.JComboBox cmbLiga;
    private javax.swing.JButton cmbTabeleMeni;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable5;
    private javax.swing.JPanel panelNapraviTurnir;
    private javax.swing.JPanel panelStatistikaIgraca;
    private javax.swing.JPanel panelTabelaTurniri;
    private javax.swing.JSpinner spinerBrojZvezdica;
    private javax.swing.JTable tabelaIgracaNaTurniru;
    private javax.swing.JTable tabelaTabela;
    private javax.swing.JTable tabelaTurnira;
    private javax.swing.JTable tabelaUtakmica;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtImeKluba;
    private javax.swing.JTextField txtNadimak;
    private javax.swing.JTextField txtNazivTurnira;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void ucitajPanel() {
        panelNapraviTurnir.setVisible(true);
        panelStatistikaIgraca.setVisible(false);
        panelTabelaTurniri.setVisible(false);
    }

    private void ucitajMiSveKlubove() {
        cmbKlub.removeAllItems();
        ArrayList<Klub> klubovi = Kontroler.getInstance().vratiMiSveKlubove();
        for (Klub klub : klubovi) {
            cmbKlub.addItem(klub);
        }
    }

    private void ucitajMiSveIgrace() {
        cmbIgrac.removeAllItems();
        ArrayList<Igrac> igraci = Kontroler.getInstance().vratiMiSveIgrace();
        for (Igrac igrac : igraci) {
            cmbIgrac.addItem(igrac);
        }
    }

    private void ucitajMiSveLige() {
        cmbLiga.removeAllItems();
        ArrayList<Liga> lige = Kontroler.getInstance().vratiMiSveLige();
        for (Liga liga : lige) {
            cmbLiga.addItem(liga);
        }
    }

    private void ucitajModelTabele() {
        tabelaIgracaNaTurniru.setModel(mtizt);
    }

    private void ucitajTurnire() {
        ArrayList<Turnir> lista = kontroler.Kontroler.getInstance().vratiMiSveTurnire();
        tabelaTurnira.setModel(mtt);
        mtt.setLista(lista);
        mtt.fireTableDataChanged();
    }

}
